### ISSUE TITLE
Add sorting functionality for score list

### ISSUE THREAD

**Issue by sjc17** [dj505/PIU-Score-Tracker#2]
Letting us filter through scores for specific difficulties, songs, ranked vs unranked, pad vs keyboard, etc... May require a bit of work.

**Comment by dj505** [comment]
Estimated to be done this by the end of next week at most. Depending on other things it might take a bit longer. I can't see it being more than just querying matching results from the database and sorting those lists by score or whichever filter

**Comment by dj505** [comment]
Functional filters have been added and will be improved over time!
